spring:
  cloud:
    gateway:
      routes:
        - id: payment
          uri: lb://PAYMENT
          predicates:
            - Path=/payment/**
          filters:
            - LoggingFilter
            - AuthenticationFilter

        - id: reporting-and-billing
          uri: lb://REPORTING-AND-BILLING
          predicates:
            - Path=/billing/**
          filters:
            - LoggingFilter
            - AuthenticationFilter

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**,/auth/**,/flat/**
          filters:
            - LoggingFilter

        - id: visitor-service
          uri: lb://VISITOR-SERVICE
          predicates:
            - Path=/visitor/**
          filters:
            - LoggingFilter
            - AuthenticationFilter

        - id: amenity-and-booking-service
          uri: lb://AMENITY-AND-BOOKING-SERVICE
          predicates:
            - Path=/visitor/**
          filters:
            - LoggingFilter
            - AuthenticationFilter

      discovery:
        locator:
          enabled: true

  application:
    name: APARTMENT-GATEWAY

  zipkin:
    base-url: http://localhost:9411

  sleuth:
    sampler:
      probability: 1.0

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/

  instance:
    prefer-ip-address : true

server:
  port : 8080